// Przenosi fonty z builda Next do motywu.
//
// Don't fetch fonts from Google — take exactly the files the old site served,
// together with the @font-face rules and the fallback metrics (size-adjust,
// ascent-override). Those metrics are what stop text from jumping before the
// webfont loads, so copying them verbatim is a layout-equivalence requirement.
//
// Usage: node extract-fonts.mjs --next ../reference-nextjs --out ../theme/assets
import { readFile, writeFile, mkdir, copyFile, readdir } from "node:fs/promises";
import path from "node:path";

const args = Object.fromEntries(
    process.argv.slice(2).reduce((acc, cur, i, arr) => (cur.startsWith("--") ? [...acc, [cur.slice(2), arr[i + 1]]] : acc), [])
);
const NEXT = args.next || "../reference-nextjs";
const OUT = args.out || "../theme/assets";

async function main() {
    const chunkDir = path.join(NEXT, ".next", "static", "chunks");
    const mediaDir = path.join(NEXT, ".next", "static", "media");

    const cssFiles = (await readdir(chunkDir)).filter((f) => f.endsWith(".css"));
    let css = "";
    for (const f of cssFiles) css += await readFile(path.join(chunkDir, f), "utf8");

    const faces = css.match(/@font-face\{[^}]*\}/g) ?? [];
    if (!faces.length) throw new Error("No @font-face rules found — has the Next project been built?");

    await mkdir(path.join(OUT, "fonts"), { recursive: true });

    const used = new Set();
    const rewritten = faces.map((face) =>
        face.replace(/url\((?:\.\.\/)*media\/([^)]+)\)/g, (_, file) => {
            used.add(file);
            return `url("../fonts/${file}")`;
        })
    );

    for (const file of used) {
        await copyFile(path.join(mediaDir, file), path.join(OUT, "fonts", file));
    }

    const out = `/*
 * Generated by tools/extract-fonts.mjs — do not edit by hand.
 * Fonts and fallback metrics come straight from the Next.js build so that
 * typography matches to the pixel.
 */

/* Font variables.
 * NOTE: check these against the original. In one project a next/font class set
 * the wrong custom property, so one variable never existed and that family
 * rendered from the @theme fallback by accident. Fixing it is safe: once the
 * webfonts load the visual result is identical. */
:root {
  --font-inter: "Inter", "Inter Fallback", sans-serif;
  --font-syne: "Syne", "Syne Fallback", sans-serif;
  --font-outfit: "Outfit", "Outfit Fallback", sans-serif;
}

${rewritten.join("\n")}
`;

    await mkdir(path.join(OUT, "css"), { recursive: true });
    await writeFile(path.join(OUT, "css", "fonts.css"), out);

    const families = [...new Set(faces.map((f) => f.match(/font-family:([^;]+)/)?.[1]))].filter(Boolean);
    console.log(`Moved ${used.size} woff2 files and ${faces.length} @font-face rules`);
    console.log(`  families: ${families.join(", ")}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
